CommBank/maestro

maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/Maestro.scala
maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/exec/Maestro.scala
maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/exec/MaestroJob.scala
maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/exec/package.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerExecution.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportExecution.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportExecution.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerExecutionSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportExecutionSpec.scala
maestro-macros/src/main/scala/au/com/cba/omnia/maestro/macros/Macros.scala

Creates an old version of MacroSupport for the pre execution code (LegacyMacroSupport).
Then creates a new version of Macro support that provides implicit views for thrift structs. The old version forced the whole trait to be tied to a specific thrift struct this instead just provides implicit methods for any thrift struct. Instead of being tied to MaestroJob this is now also provided as part of `exec.Maestro._`.

Makes MacroSupport more generic.

---

maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/exec/Maestro.scala
maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/exec/package.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/exec/QueryExecution.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/exec/UploadExecution.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/Upload.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/upload/Input.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/upload/Push.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/UploadSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/upload/InputSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/upload/PushSpec.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerCascade.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerExecution.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerUploadExample.scala
project/build.scala
version.sbt

Takes advantage of the Hive monad from Ebenezer and all corresponding changes.
* `Result` is now in omnitool instead of permafrost.
* Use `fold` on `Result` instead of pattern matching.
* `fromHive` for Execution.
* Deprecated `QueryExecution`.
* Added Hive and Hdfs to api package.
This also closes #250.

Hive monad

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/hive/HiveTable.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/exec/ViewExecutionSpec.scala
project/build.scala

Adds the ability to append to an unpartitioned hive table. Since Hadoop doesn't allow for writing to a directory that already exists we instead write to a temporary folder, munge the file names and then copy them across.

Adds append for unpartitioned hive tables using the execution api.

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/SqoopExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/SqoopImportExecutionSpec.scala
project/build.scala

When importing data using Sqoop using a query Sqoop creates a java class and jar with a generic name. If there are 2 sqoop imports in the same job they will have the same name and clash causing the second import to fail.
This sets a unique class name for each sqoop job.
This closes #286.

Multiple sqoop queries fix

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/CombinedSequenceFile.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/Paths.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/LoadExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/LoadExecutionSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/LoadViewExecutionSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/StringPairSupport.scala

We also switch to using a compact encoding for the temp sequence files.
The load pipe split size is configurable.
NOTE: I have not yet tested this on the cluster against a real load, but will do so before merging to master.

The load return pipe provides a smaller number of larger splits

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/LoadExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/LoadExecutionSpec.scala
project/build.scala

This fix just always expands the `sources` passed to `load` to the full paths for all files.

Generate key path fix

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/ViewExecution.scala
project/build.scala
project/plugins.sbt
version.sbt

CDH5 upgrade and force view execution to create the hive database.
This prevents the concurrent attempt to create the database within
HiveTap from failing and crashing the job.

CDH5 upgrade

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/scalding/RichExecutionSpec.scala
version.sbt

Changes the internals of `RichExecution` `fromHive`, `fromHdfs` and `fromEither` to provide a more useful stack trace. The stack trace now shows the location that `fromHdfs` or `fromHive` where called. This closes #326.
Also adds `fromResult`.

Better stack trace for `RichExecution.from...` and adds `RichExecution.fromResult`

---

maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/package.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/MaestroExecution.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/MaestroJob.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/scalding/MaestroExecutionSpec.scala
version.sbt

This should make some of the control flows much nicer. In particular when you want to return JobNotReady and then stop.

Adds ability to set JobNotReady and JobFailure as execution errors and recover them again.

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/time/TimeSource.scala
version.sbt

This fixes #265. Although this is arguably a regression,
it is in line with our other dates. This commit aims for consistency,
rather than providing a solution to our time zone issues.

TimeSource.predetermined does not handle timezones

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/MaestroConfig.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerExecutionSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerJobSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportExecutionSpec.scala
version.sbt

All data loads use hive database with a prefix. Adding the support in MaestroConfig.

Adding command line arguments to get hive database prefix

---

maestro-api/src/test/scala/au/com/cba/omnia/maestro/api/test/SynxtaxSpec.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala
version.sbt

Changes RichExecutionOps to not pull in implicit conversions to `MonadOps` and `BindOps`.
`RichExecutionOps` was extending `ToResultantMonadOps` which also extends `ToMonadOps` and `ToPlusOps`. Since `RichExecutionOps` is not a companion object the implicits provided by `ToMonadOps` from `ToResultantOps` clashed with the `ToMonadOps` imported from Scalaz.
This changes `RichExecutionOps` to not extends `ToResultantMonadOps` and instead just provide an implicit conversion to `ResultantMonadOps`.
This fixes #372.

Fixes `>>=` not work on Execution

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/MaestroJob.scala
version.sbt

The timeout value is set to 60 seconds which seems sufficiently high but I am happy to change it.

Adding a timeout for fetching job counters

---

maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/Classifier.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/Infer.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/Schema.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/Squash.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/Tope.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/commands/Infer.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/jobs/Check.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/schema/ColumnSpec.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/schema/Format.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/schema/Histogram.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/schema/Load.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/schema/Parser.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/schema/TableSpec.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/taste/Load.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/taste/Parser.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/taste/Row.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/taste/Sample.scala
maestro-schema/src/main/scala/au/com/cba/omnia/maestro/schema/taste/Table.scala
project/build.scala

The update to Scala 2.11 caused some warnings in the schema project compilation. These related to:
- unused imports,
- one "discarded non-Unit value" due to changing a mutable map, and
- deprecation of the Scala parser combinators from the core library.
This PR removes those warnings.

Fix schema compile warnings

---

project/build.scala

This allows ETL projects to use modified `setupHiveTestTable` function so that user can pass delimiter while creating a hive test table.

Ebenezer version bump

---

project/plugins.sbt

`maestro` has stopped building successfully in the last week because it's unable to resolve `libthrift;0.9.0-cdh-5-2`. `libthrift` is required by the `humbug-plugin`, and the resolver for this dependency must be added explicitly to the list of plugin resolvers of `maestro`. Strangely, the last commit https://github.com/CommBank/maestro/commit/92c54223ed98c7e9150632a38ee89b2fca357cb2 passed on Travis at the time, but in the last week this error has turned up with no code changes to `maestro`, `uniform`, or `humbug` inbetween.
Adding the Cloudera repository to the list of plugin resolvers should fix this.
Error message from https://travis-ci.org/#L335:
```
...
[warn] 	module not found: org.apache.thrift#libthrift;0.9.0-cdh5-2
[warn] ==== typesafe-ivy-releases: tried
[warn] …
```

Added missing Cloudera plugin resolver to fix build.

---

maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/hive/HiveTable.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/ViewExecutionSpec.scala
version.sbt

It removes `MSCK REPAIR TABLE` statement since it is not needed. The
current use of it did not set the database and was broken.
It also changes the overwrite parts of the code to handle the case where
a table exists in the metastore but the underlying directory has been
deleted.
This fixes #426.

Fixes `HiveTable.writeExecution` bugs.

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/hdfs/MaestroHdfs.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/hdfs/MaestroHdfsSpec.scala

Ordered file listings are guaranteed by Permafrost >= 0.8.1.
Fixes #386.

Simplify MaestroHdfsSpec with assumption of ordered files

---

project/build.scala
version.sbt

Macros only require scala-reflect. Avoid listing scald-compiler as a dependency, since this will contribute an unnecessary transitive dependency to downstream projects.

Removes unneeded dependency on scala-compiler

---

maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/hive/HiveTable.scala
maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/scalding/ConfHelper.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/ViewExecutionSpec.scala
version.sbt

Use scalding's [`UniqueID`](https://github.com/twitter/scalding/blob/0.13.1/scalding-core/src/main/scala/com/twitter/scalding/Stats.scala#L92) (which incorporates an atomic counter with the system time in millis) for more guaranteed unique part file names to avoid race condition that can arise when zipping executions that append to the same location.

Avoid race condition when creating unique names in parallel

---

maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportJob.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportJobSpec.scala
project/build.scala
version.sbt

Updating parlour version to support replace/removal of new line and control-A character from string columns during Sqoop import

Updating parlour version and test case for sqoop import

---

maestro-macros/src/main/scala/au/com/cba/omnia/maestro/macros/FieldsMacro.scala
maestro-macros/src/main/scala/au/com/cba/omnia/maestro/macros/Macros.scala
maestro-macros/src/test/scala/au/com/cba/omnia/maestro/macros/FieldsMacroSpec.scala
version.sbt

This is a proposal that will allow generic functions with `T <: ThriftStruct` to obtain a list of fields for `T`, in the same order that they would be written by `Encode`.
An example of how this is useful (and the motivating use case for this PR) is producing a header for a text file.
There are similarities with the existing `Tag` typeclass, but that is difficult to apply to the example above. In particular, it is impossible to use `Tag` without knowing at least the _number_ of fields.
I acknowledge that the name clash between the existing `Fields` macro and the new `Fields` typeclass is potentially confusing, but conceptually (albeit not technically) it is a generalisation of the existing interface, from being able to write:
Fields[MyThrift].AllFields
to being able to extract the same …

Adds Fields typeclass and implicit instances

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/partition/Partition.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/time/TimeSource.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/validate/Validator.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/validate/CheckSpec.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/LoadExecutionSpec.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/ViewExecutionSpec.scala
version.sbt

Addresses #497.
This includes some small API changes, just to force existing client code with unintended time zone dependencies to be revisited, similar to #483:
- `Check.isDate` now throws an exception if the pattern is time-sensitive and no time zone is specified.  Replace with `isDateUTC` or `isDateSydney` or explicitly give the intended time zone.
- `TimeSource.now` now requires an additional argument for the time zone.  For convenience, use `nowUTC` or `nowSydney`.

Fix byHour daylight savings transition and other time zone dependencies.

---

README.md

The design document is of interest in the current ETL working group process, for historical context, but was less obvious.

Added direct README link to the design document.

---

maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/scalding/MaestroExecution.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/scalding/MaestroExecutionSpec.scala
version.sbt

This is to Support `JobNotReadyException` and `JobFailureException` wrapped in `ResultException`  returning expected values during error recovery.

Support jobnotready and jobfailures wrapped in result exception during error recovery

---

maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJob.scala
maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportJob.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/SqoopExportExecutionSpec.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/SqoopImportExecutionSpec.scala
project/build.scala
project/plugins.sbt
version.sbt

This will be merged into a new release branch: *cdh-513*. CDH 5.13.0 is not yet productionised in Omnia and won't be for a few months.
Driven by [Uniform PR #103](https://github.com/CommBank/uniform/pull/103) .
Upgrades libraries to CDH 5.13.0, as per:
- https://archive.cloudera.com/cdh5/cdh/5/hadoop/hadoop-project-dist/hadoop-common/dependency-analysis.html
- https://www.cloudera.com/documentation/enterprise/release-notes/topics/cm_vd_cdh_package_tarball_513.html

CDH 5.13.0
