maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/hive/HiveTable.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/SqoopExecution.scala

* Removes `write` and `sink` from HiveTable since they are broken and unused with the new API.
* Refactors SqoopExecution to use `withSubConfig`.

Minor API cleanup

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/LoadExecution.scala

Work around #300 until we figure out what the problem is and can fix it.

Uses cascading-counter for filtering instead of scalding.

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/UploadExecution.scala

minor fixes to upload logging

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/MaestroConfig.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/validate/Validator.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/validate/ValidatorSpec.scala

Adds a Validator that never fails.

---

maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/LoadViewExecutionSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/ViewExecutionSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerExecutionSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportExecutionSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopImportExecutionSpec.scala
maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/TransformExecutionSpec.scala
project/build.scala
version.sbt

* Reduces the parquet log output
* Reduces the assembly log output

Reduces log spam

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/codec/Tag.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/LoadExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/LoadExecutionSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/StringPairSupport.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/StringTripleSupport.scala
maestro-core/src/test/thrift/scrooge/StringTriple.thrift
maestro-macros/src/main/scala/au/com/cba/omnia/maestro/macros/TagMacro.scala
maestro-macros/src/test/scala/au/com/cba/omnia/maestro/macros/TagMacroSpec.scala
version.sbt

Tagging now fails if the number cells does not match the number of fields.
This closes #147.

Changes the Tag to handle failures.

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/SqoopExecution.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/UploadExecution.scala

standardise on slf4j logging

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/data/Accessor.scala
maestro-macros/src/main/scala/au/com/cba/omnia/maestro/macros/FieldsMacro.scala

Replaces per-field closures with an Accessor function class instantiated for each field.

Reduce class file generation (#317)

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/scalding/RichExecutionSpec.scala

This includes the work Rowan did to turn Execution into a ResultantMonad.
I picked this up because I'm looking at coming up with a generic load and I was missing some syntax on Execution that this provides.

Execution resultant monad

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/MaestroExecution.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/task/LoadExecution.scala
version.sbt

Added some more functionality to LoadInfo and MaestroExecution to assist with improving control flow code.

More control flow syntax

---

maestro-api/src/main/scala/au/com/cba/omnia/maestro/api/package.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/hdfs/Guard.scala
maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/hdfs/MaestroHdfs.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/hdfs/GuardSpec.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/hdfs/MaestroHdfsSpec.scala
project/build.scala
version.sbt

This fixes #285, as the new methods return Hdfs actions.

Adds HdfsUtils and deprecates Guard

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/hive/HiveTable.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/task/ViewExecutionSpec.scala

This branch implements a fix for #382.

viewHive overwrite

---

maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/task/HeaderTrailer.scala
maestro-scalding/src/test/resources/trailer-parser-empty-lines/local-ingest/dataFeed/normal/mydomain/mytable_20141118.dat
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/task/HeaderTrailerSpec.scala
project/build.scala
version.sbt

Adds header and trailer parsing for files on HDFS.

---

maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/data/Field.scala
maestro-core/src/test/scala/au/com/cba/omnia/maestro/core/data/FieldSpec.scala

I am not sure if the correct word for this is *lift*

Ability to lift fields to a larger enclosing structure

---

project/build.scala
version.sbt

Update the version of Thermometer to the latest, Which was not updated for a while

Update the version of Thermometer to the latest

---

maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/hive/HiveTable.scala
version.sbt

And ignoring hidden files at the root

Reverting deletions of _temporary folder

---

README.md

Fix some outdated links

---

project/build.scala
version.sbt

This parlour version incorporates the direct mode option.

Bumped Parlour version to 1.11.1-20160105030640-0ce6193

---

maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/scalding/RichExecution.scala
maestro-scalding/src/test/scala/au/com/cba/omnia/maestro/scalding/RichExecutionSpec.scala
version.sbt

Conversion between scalaz.effect.IO and scalding Execution

IO -> Execution

---

project/build.scala
version.sbt

Updating the beeswax and ebenezer version to get the support for nested structs

updating beeswax and ebenezer version to get the support for structs
